ERROR:root:Exception in main()
Traceback (most recent call last):
  File "C:/Users/condrow/Desktop/device_alarm/test.py", line 14, in <module>
    exit(main())
NameError: name 'main' is not defined
ERROR:root:Exception in main()
Traceback (most recent call last):
  File "C:/Users/condrow/Desktop/device_alarm/test.py", line 14, in <module>
    exit(main())
NameError: name 'main' is not defined
ERROR:root:Exception in main()
Traceback (most recent call last):
  File "C:/Users/condrow/Desktop/device_alarm/test.py", line 14, in <module>
    exit(main())
NameError: name 'main' is not defined
INFO:root:info in main()
ERROR:root:error in main()
ERROR:root:Exception in main()
Traceback (most recent call last):
  File "C:\Users\condrow\Desktop\device_alarm\monitor.py", line 32, in read_db
    with open(self.device_mac_list) as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'databas.csv'
ERROR:root:Exception in main()
Traceback (most recent call last):
  File "C:\Users\condrow\Desktop\device_alarm\monitor.py", line 32, in read_db
    with open(self.device_mac_list) as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'databas.csv'
ERROR:root:[DeviceSniff][read_db]
Traceback (most recent call last):
  File "C:\Users\condrow\Desktop\device_alarm\monitor.py", line 32, in read_db
    with open(self.device_mac_list) as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'databas.csv'
